@echo off
echo Creating Azure Web App ezsearch-hub...
call az webapp create --name ezsearch-hub --resource-group EZsearch-rg --plan EZsearch-plan --runtime "NODE|22-lts"
echo Setting startup command...
call az webapp config set --resource-group EZsearch-rg --name ezsearch-hub --startup-file "node server/index.js"
echo Deploying code zip...
call az webapp deploy --resource-group EZsearch-rg --name ezsearch-hub --src-path . --type zip
